<<<<<<< HEAD
spring:
  application:
    name: payment-service


server:
  port: 8090


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

  instance:
    prefer-ip-address: true
      
    

management:
  endpoints:
    web:
      exposure:
        include: "*"
=======
spring:
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
  application:
    name: payment-service    
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 200
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
    port: 9091
>>>>>>> authentication
