server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    gateway:
      loadbalancer:
        ribbon:
          enabled: false
      discovery:
          locator:
            enabled: true
            lowerCaseServiceId: true

      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
          filters:
            - StripPrefix=1

        - id: discovery-service
          uri: lb://discovery-service
          predicates:
            - Path=/discovery-service/**
          filters:
            - StripPrefix=1

        - id: eureka
          uri: lb://discovery-service
          predicates:
            - Path=/eureka/**

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/event-service/**
          filters:
            - StripPrefix=1

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authentication-service/**
          filters:
            - StripPrefix=1
            
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
    healthcheck:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"