spring:
    application:
        name: gateway-service
    config:
        import: optional:configserver:http://localhost:8888
    cloud:
        gateway:
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowedOrigins: "http://localhost:3000"
                        allowedMethods: "*"
server:
    port: 8765
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka

