server:
  port: 8760

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
          filters:
            - StripPrefix=1
        - id: discovery-service
          uri: lb://discovery-service
          predicates:
            - Path=/discovery-service/**
          filters:
            - StripPrefix=1
        - id: eureka
          uri: lb://discovery-service
          predicates:
            - Path=/eureka/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/event-service/**
          filters:
            - StripPrefix=1
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
    healthcheck:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"