spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

