spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.02

management:
  endpoints:
    web:
      exposure:
        include: '*'