<<<<<<< HEAD
spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false

  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"    
=======
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
>>>>>>> authentication
