import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import NextTopLoader from "nextjs-toploader";
import Providers from "@/lib/Providers";
import { Toaster } from "sonner";


const robo = Roboto_Mono({
	subsets: ["latin"],
	weight: ["600"],
	variable: "--font-roboto",
});
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} ${robo.variable}`}>
				<Providers>
					<NextUIProvider>
						<NextTopLoader height={4}  color="purple" />
						{children}
					</NextUIProvider>
				</Providers>
				<Toaster richColors={true} />
			</body>
		</html>
	);
}
