
services:

  # zookeeper:
  #   image: 'bitnami/zookeeper:latest'
  #   container_name: zookeeper
  #   ports:
  #     - '2181:2181'
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #   depends_on:
  #     authentication-service-db:
  #       condition: service_healthy
  #     event-service-db:
  #       condition: service_healthy

  # kafka:
  #   image: 'bitnami/kafka:latest'
  #   container_name: kafka
  #   ports:
  #     - '9092:9092'
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092  
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes 
  #     - KAFKA_CREATE_TOPICS=Tickex
  #   depends_on:
  #     - zookeeper
      
  client:
    image: 'madockerhub/tickex-client'
    container_name: client
    expose:
      - '3000'
    ports:
      - '3000:3000'    
            
  gateway-service:
    image: 'madockerhub/tickex-gateway-service'
    container_name: gateway-service
    ports:
      - '8888:8888'
    depends_on:
      - event-service
      - authentication-service
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka


  discovery-service:
    image: 'madockerhub/tickex-discovery-service'
    container_name: discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'


  authentication-service-db: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: authentication-service-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1234Strong!Password
    ports:
      - '1433:1433'
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "1234Strong!Password" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 20
      start_period: 10s 


  event-service-db: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: event-service-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1234Strong!Password
    ports:
      - '1434:1433'
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "1234Strong!Password" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 20
      start_period: 10s


  authentication-service:
    image: 'madockerhub/tickex-authentication-service'
    container_name: authentication-service
    environment:
      - DB_HOST=authentication-service-db
      - DB_NAME=Authentication
      - DB_SA_PASSWORD=1234Strong!Password
    depends_on:
      authentication-service-db:
        condition: service_healthy
    ports:
      - '8085:8080'
      - '8086:8081'


  event-service:
    image: 'madockerhub/tickex-event-service'
    container_name: event-service
    environment:
      - DB_HOST=event-service-db
      - DB_NAME=Events
      - DB_SA_PASSWORD=1234Strong!Password
    depends_on:
      event-service-db:
        condition: service_healthy
    ports:
      - '8080:8080'
      - '8081:8081'


  payment-service:
    image: 'madockerhub/tickex-payment-service'
    container_name: payment-service
    expose:
      - '8090'
    depends_on:
      - gateway-service
    ports:
      - '8090:8090'    
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka



      