networks:
  tickexNetwork:
    name: tickexNetwork

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - tickexNetwork

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./Kafka:/bitnami/kafka
    networks:
      - tickexNetwork
    depends_on:
      - zookeeper
      
  discovery-service:
      build: ./discovery-service
      container_name: tickex-discovery-service
      ports:
        - '8761:8761'
      expose:
        -  '8761'
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]  
        interval: 10s
        retries: 10
      networks:
        - tickexNetwork
      depends_on:
        - kafka  
    
  gateway-service:
      build: ./gateway-service
      container_name: tickex-gateway-service
      ports:
        - '8765:8765'
      expose:
        -  '8765'
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8765/actuator/health" ]  
        interval: 10s
        retries: 10
      networks:
        - tickexNetwork
      depends_on:
        - discovery-service

    
 