// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using event_service.Data;

#nullable disable

namespace event_service.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240507144629_final")]
    partial class final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ticket", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.HasKey("EventId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("event_service.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Seats")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FFD700",
                            EventId = 1,
                            Name = "Gold",
                            Price = 1000f,
                            Seats = 100
                        },
                        new
                        {
                            Id = 2,
                            Color = "#C0C0C0",
                            EventId = 1,
                            Name = "Silver",
                            Price = 500f,
                            Seats = 200
                        },
                        new
                        {
                            Id = 3,
                            Color = "#CD7F32",
                            EventId = 1,
                            Name = "Bronze",
                            Price = 300f,
                            Seats = 300
                        },
                        new
                        {
                            Id = 4,
                            Color = "#FFD700",
                            EventId = 2,
                            Name = "Gold",
                            Price = 1000f,
                            Seats = 100
                        },
                        new
                        {
                            Id = 5,
                            Color = "#C0C0C0",
                            EventId = 2,
                            Name = "Silver",
                            Price = 500f,
                            Seats = 200
                        },
                        new
                        {
                            Id = 6,
                            Color = "#CD7F32",
                            EventId = 2,
                            Name = "Bronze",
                            Price = 300f,
                            Seats = 300
                        },
                        new
                        {
                            Id = 7,
                            Color = "#FFD700",
                            EventId = 3,
                            Name = "Gold",
                            Price = 1000f,
                            Seats = 100
                        },
                        new
                        {
                            Id = 8,
                            Color = "#C0C0C0",
                            EventId = 3,
                            Name = "Silver",
                            Price = 500f,
                            Seats = 200
                        },
                        new
                        {
                            Id = 9,
                            Color = "#CD7F32",
                            EventId = 3,
                            Name = "Bronze",
                            Price = 300f,
                            Seats = 300
                        },
                        new
                        {
                            Id = 10,
                            Color = "#FFD700",
                            EventId = 4,
                            Name = "Gold",
                            Price = 1000f,
                            Seats = 100
                        },
                        new
                        {
                            Id = 11,
                            Color = "#C0C0C0",
                            EventId = 4,
                            Name = "Silver",
                            Price = 500f,
                            Seats = 200
                        },
                        new
                        {
                            Id = 12,
                            Color = "#CD7F32",
                            EventId = 4,
                            Name = "Bronze",
                            Price = 300f,
                            Seats = 300
                        },
                        new
                        {
                            Id = 13,
                            Color = "#FFD700",
                            EventId = 5,
                            Name = "Gold",
                            Price = 1000f,
                            Seats = 100
                        },
                        new
                        {
                            Id = 14,
                            Color = "#C0C0C0",
                            EventId = 5,
                            Name = "Silver",
                            Price = 500f,
                            Seats = 200
                        },
                        new
                        {
                            Id = 15,
                            Color = "#CD7F32",
                            EventId = 5,
                            Name = "Bronze",
                            Price = 300f,
                            Seats = 300
                        },
                        new
                        {
                            Id = 16,
                            Color = "#FFD700",
                            EventId = 6,
                            Name = "Gold",
                            Price = 1000f,
                            Seats = 100
                        },
                        new
                        {
                            Id = 17,
                            Color = "#C0C0C0",
                            EventId = 6,
                            Name = "Silver",
                            Price = 500f,
                            Seats = 200
                        },
                        new
                        {
                            Id = 18,
                            Color = "#CD7F32",
                            EventId = 6,
                            Name = "Bronze",
                            Price = 300f,
                            Seats = 300
                        },
                        new
                        {
                            Id = 19,
                            Color = "#FFD700",
                            EventId = 7,
                            Name = "Gold",
                            Price = 1000f,
                            Seats = 100
                        },
                        new
                        {
                            Id = 20,
                            Color = "#C0C0C0",
                            EventId = 7,
                            Name = "Silver",
                            Price = 500f,
                            Seats = 200
                        },
                        new
                        {
                            Id = 21,
                            Color = "#CD7F32",
                            EventId = 7,
                            Name = "Bronze",
                            Price = 300f,
                            Seats = 300
                        },
                        new
                        {
                            Id = 22,
                            Color = "#FFD700",
                            EventId = 8,
                            Name = "Gold",
                            Price = 1000f,
                            Seats = 100
                        },
                        new
                        {
                            Id = 23,
                            Color = "#C0C0C0",
                            EventId = 8,
                            Name = "Silver",
                            Price = 500f,
                            Seats = 200
                        },
                        new
                        {
                            Id = 24,
                            Color = "#CD7F32",
                            EventId = 8,
                            Name = "Bronze",
                            Price = 300f,
                            Seats = 300
                        },
                        new
                        {
                            Id = 25,
                            Color = "#FFD700",
                            EventId = 9,
                            Name = "Gold",
                            Price = 1000f,
                            Seats = 100
                        },
                        new
                        {
                            Id = 26,
                            Color = "#C0C0C0",
                            EventId = 9,
                            Name = "Silver",
                            Price = 500f,
                            Seats = 200
                        },
                        new
                        {
                            Id = 27,
                            Color = "#CD7F32",
                            EventId = 9,
                            Name = "Bronze",
                            Price = 300f,
                            Seats = 300
                        },
                        new
                        {
                            Id = 28,
                            Color = "#FFD700",
                            EventId = 10,
                            Name = "Gold",
                            Price = 1000f,
                            Seats = 100
                        },
                        new
                        {
                            Id = 29,
                            Color = "#C0C0C0",
                            EventId = 10,
                            Name = "Silver",
                            Price = 500f,
                            Seats = 200
                        },
                        new
                        {
                            Id = 30,
                            Color = "#CD7F32",
                            EventId = 10,
                            Name = "Bronze",
                            Price = 300f,
                            Seats = 300
                        });
                });

            modelBuilder.Entity("event_service.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("event_service.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DesignId")
                        .HasColumnType("integer");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Is_finished")
                        .HasColumnType("boolean");

                    b.Property<bool>("On_sell")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganizerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Santiago Bernabéu",
                            City = "Madrid",
                            CreationDate = new DateTime(2024, 5, 7, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4443),
                            Description = "Champions league semi finals",
                            DesignId = 0,
                            Duration = 2f,
                            EventDate = new DateTime(2024, 5, 7, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4442),
                            EventType = "Sports",
                            Is_finished = false,
                            On_sell = true,
                            OrganizerId = "1",
                            Poster = "https://firebasestorage.googleapis.com/v0/b/tickex-20fa7.appspot.com/o/images%2FScreenshot%20from%202024-04-15%2017-01-42.png-7abac09f-7c7d-4101-ac2b-703ba7a55fb6?alt=media&token=70fad095-672c-4226-b0af-8670422be521",
                            Time = "20h00",
                            Title = "REAL MADRID VS BAYERN MUNICH"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Royal Theater Rabat",
                            City = "Rabat",
                            CreationDate = new DateTime(2024, 5, 7, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4467),
                            Description = "Exclusive fashion show showcasing latest trends",
                            DesignId = 0,
                            Duration = 3f,
                            EventDate = new DateTime(2024, 9, 4, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4463),
                            EventType = "Fashion",
                            Is_finished = false,
                            On_sell = true,
                            OrganizerId = "1",
                            Poster = "https://firebasestorage.googleapis.com/v0/b/tickex-20fa7.appspot.com/o/images%2FScreenshot%20from%202024-04-15%2017-01-42.png-7abac09f-7c7d-4101-ac2b-703ba7a55fb6?alt=media&token=70fad095-672c-4226-b0af-8670422be521",
                            Time = "19h00",
                            Title = "Fashion Show"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Casablanca International Convention Center",
                            City = "Casablanca",
                            CreationDate = new DateTime(2024, 5, 7, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4482),
                            Description = "Cutting-edge technology conference",
                            DesignId = 0,
                            Duration = 4f,
                            EventDate = new DateTime(2024, 6, 6, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4481),
                            EventType = "Technology",
                            Is_finished = false,
                            On_sell = true,
                            OrganizerId = "1",
                            Poster = "https://firebasestorage.googleapis.com/v0/b/tickex-20fa7.appspot.com/o/images%2FScreenshot%20from%202024-04-15%2017-01-42.png-7abac09f-7c7d-4101-ac2b-703ba7a55fb6?alt=media&token=70fad095-672c-4226-b0af-8670422be521",
                            Time = "10h00",
                            Title = "Tech Conference"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Palmeraie Marrakech",
                            City = "Marrakech",
                            CreationDate = new DateTime(2024, 5, 7, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4497),
                            Description = "Annual music festival featuring top artists",
                            DesignId = 0,
                            Duration = 2f,
                            EventDate = new DateTime(2024, 7, 6, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4496),
                            EventType = "Music",
                            Is_finished = false,
                            On_sell = true,
                            OrganizerId = "1",
                            Poster = "https://firebasestorage.googleapis.com/v0/b/tickex-20fa7.appspot.com/o/images%2FScreenshot%20from%202024-04-15%2017-01-42.png-7abac09f-7c7d-4101-ac2b-703ba7a55fb6?alt=media&token=70fad095-672c-4226-b0af-8670422be521",
                            Time = "18h00",
                            Title = "Music Festival"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Tangier Art Gallery",
                            City = "Tangier",
                            CreationDate = new DateTime(2024, 5, 7, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4511),
                            Description = "Contemporary art exhibition",
                            DesignId = 0,
                            Duration = 2.5f,
                            EventDate = new DateTime(2024, 8, 5, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4510),
                            EventType = "Art",
                            Is_finished = false,
                            On_sell = true,
                            OrganizerId = "1",
                            Poster = "https://firebasestorage.googleapis.com/v0/b/tickex-20fa7.appspot.com/o/images%2FScreenshot%20from%202024-04-15%2017-01-42.png-7abac09f-7c7d-4101-ac2b-703ba7a55fb6?alt=media&token=70fad095-672c-4226-b0af-8670422be521",
                            Time = "15h00",
                            Title = "Art Exhibition"
                        },
                        new
                        {
                            Id = 6,
                            Address = "ENSA Agadir",
                            City = "Agadir",
                            CreationDate = new DateTime(2024, 5, 7, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4561),
                            Description = "Annual career fair organized by ENSA",
                            DesignId = 0,
                            Duration = 4f,
                            EventDate = new DateTime(2024, 6, 6, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4560),
                            EventType = "Career",
                            Is_finished = false,
                            On_sell = true,
                            OrganizerId = "2",
                            Poster = "https://firebasestorage.googleapis.com/v0/b/tickex-20fa7.appspot.com/o/images%2FScreenshot%20from%202024-04-15%2017-01-42.png-7abac09f-7c7d-4101-ac2b-703ba7a55fb6?alt=media&token=70fad095-672c-4226-b0af-8670422be521",
                            Time = "09h00",
                            Title = "ENSA Career Fair"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Casablanca International Convention Center",
                            City = "Casablanca",
                            CreationDate = new DateTime(2024, 5, 7, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4577),
                            Description = "Cutting-edge technology conference",
                            DesignId = 0,
                            Duration = 5f,
                            EventDate = new DateTime(2024, 7, 6, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4576),
                            EventType = "Technology",
                            Is_finished = false,
                            On_sell = true,
                            OrganizerId = "2",
                            Poster = "https://firebasestorage.googleapis.com/v0/b/tickex-20fa7.appspot.com/o/images%2FScreenshot%20from%202024-04-15%2017-01-42.png-7abac09f-7c7d-4101-ac2b-703ba7a55fb6?alt=media&token=70fad095-672c-4226-b0af-8670422be521",
                            Time = "10h00",
                            Title = "Tech Conference 2024"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Palmeraie Marrakech",
                            City = "Marrakech",
                            CreationDate = new DateTime(2024, 5, 7, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4591),
                            Description = "Annual music festival featuring top artists",
                            DesignId = 0,
                            Duration = 8f,
                            EventDate = new DateTime(2024, 8, 5, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4590),
                            EventType = "Music",
                            Is_finished = false,
                            On_sell = true,
                            OrganizerId = "2",
                            Poster = "https://firebasestorage.googleapis.com/v0/b/tickex-20fa7.appspot.com/o/images%2FScreenshot%20from%202024-04-15%2017-01-42.png-7abac09f-7c7d-4101-ac2b-703ba7a55fb6?alt=media&token=70fad095-672c-4226-b0af-8670422be521",
                            Time = "18h00",
                            Title = "Music Festival"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Marrakech Conference Center",
                            City = "Marrakech",
                            CreationDate = new DateTime(2024, 5, 7, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4605),
                            Description = "Annual startup summit bringing together entrepreneurs and investors",
                            DesignId = 0,
                            Duration = 7f,
                            EventDate = new DateTime(2024, 9, 4, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4604),
                            EventType = "Startup",
                            Is_finished = false,
                            On_sell = true,
                            OrganizerId = "2",
                            Poster = "https://firebasestorage.googleapis.com/v0/b/tickex-20fa7.appspot.com/o/images%2FScreenshot%20from%202024-04-15%2017-01-42.png-7abac09f-7c7d-4101-ac2b-703ba7a55fb6?alt=media&token=70fad095-672c-4226-b0af-8670422be521",
                            Time = "09h00",
                            Title = "Startup Summit"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Casablanca Food Park",
                            City = "Casablanca",
                            CreationDate = new DateTime(2024, 5, 7, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4621),
                            Description = "Celebration of culinary delights with food stalls and cooking demonstrations",
                            DesignId = 0,
                            Duration = 6f,
                            EventDate = new DateTime(2024, 10, 4, 15, 46, 28, 717, DateTimeKind.Local).AddTicks(4620),
                            EventType = "Food",
                            Is_finished = false,
                            On_sell = true,
                            OrganizerId = "2",
                            Poster = "https://firebasestorage.googleapis.com/v0/b/tickex-20fa7.appspot.com/o/images%2FScreenshot%20from%202024-04-15%2017-01-42.png-7abac09f-7c7d-4101-ac2b-703ba7a55fb6?alt=media&token=70fad095-672c-4226-b0af-8670422be521",
                            Time = "12h00",
                            Title = "Food Festival"
                        });
                });

            modelBuilder.Entity("event_service.Entities.Image", b =>
                {
                    b.Property<string>("url")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.HasKey("url");

                    b.HasIndex("EventId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("event_service.Entities.Organizer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizers");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Email = "anas@gmail.com",
                            OrganizationName = "",
                            PhoneNumber = "1234567890",
                            firstname = "anas",
                            lastname = "chatt"
                        },
                        new
                        {
                            Id = "2",
                            Email = "aimane@gmail.com",
                            OrganizationName = "ENSA",
                            PhoneNumber = "1234567890",
                            firstname = "aimane",
                            lastname = "chanaa"
                        });
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.HasOne("event_service.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("event_service.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("event_service.Entities.Category", b =>
                {
                    b.HasOne("event_service.Entities.Event", "Event")
                        .WithMany("Categories")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("event_service.Entities.Event", b =>
                {
                    b.HasOne("event_service.Entities.Organizer", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("event_service.Entities.Image", b =>
                {
                    b.HasOne("event_service.Entities.Event", "Event")
                        .WithMany("Images")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("event_service.Entities.Event", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
