name:  authentication-service CI/CD
on:
  push:
    branches: [ "test-workflows" ]


jobs:
  build:
    runs-on: ubuntu-latest    
    steps:

    - uses: actions/checkout@v3

    - name: Build the Docker image
      with:
        context: ./server/authentication-service
        run: docker build . -t madockerhub/tickex-authentication-service:latest

    - name: login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  
      
    - name: push image
      uses: docker/build-push-action@v5
      with:
        context: ./server/authentication-service
        dockerfile: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tickex-gateway-service:latest   