name: authentication-service CI/CD
on:
  push:
    branches: [ "dev" ]

jobs:
  build-push:
    runs-on: ubuntu-latest    
    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: Build .NET application
        run: dotnet build ./server/authentication-service
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      

      # Corrected step for pushing the image
      - name: Push image
        uses: docker/build-push-action@v5
        with:
          context: ./server/authentication-service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tickex-authentication-service:latest
