name: discovery-service CI/CD Pipeline

on:
  push:
    branches:
      - dev


jobs:
  build-deploy:
    name: Build test and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Test and Build
        run: |
          cd server/discovery-service
          mvn clean install
        working-directory: ./  

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push image
        uses: docker/build-push-action@v5
        with:
          context: ./server/discovery-service
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tickex-discovery-service:latest
